# Generated by Django 5.1.4 on 2026-08-24 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('send_sms', models.BooleanField(default=False, help_text='If checked, fans out an SMS to affected residents when this alert is saved.')),
                ('sms_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, help_text='Leave blank to broadcast LGA-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='wards.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
