# Generated by Django 5.1.4 on 2026-08-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('language', 'Language'), ('festival', 'Festival'), ('proverb', 'Proverb'), ('folklore', 'Folklore'), ('custom', 'Custom / Tradition')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('local_text', models.CharField(blank=True, help_text='The Idoma (or local dialect) word/phrase/proverb itself', max_length=300)),
                ('english_meaning', models.TextField()),
                ('context_notes', models.TextField(blank=True, help_text="When/how it's used, regional variation across Agatu wards, etc.")),
                ('audio_pronunciation', models.FileField(blank=True, null=True, upload_to='culture/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='culture/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Culture entries',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text="e.g. 'Executive Chairman, Agatu LGA', 'District Head', 'Och'Agatu'", max_length=150)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='leaders/portraits/')),
                ('start_year', models.PositiveIntegerField(help_text='Year tenure began')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Leave blank if currently in office', null=True)),
                ('biography', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(blank=True, help_text='Optional â€” for ward-level or district-level leaders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders', to='wards.ward')),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='history.leader')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
    ]
