# Generated by Django 5.1.4 on 2026-08-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short overview: geography, dominant clans, notable settlements.')),
                ('headquarters_town', models.CharField(blank=True, max_length=150)),
                ('is_lga_headquarters', models.BooleanField(default=False, help_text='True only for the ward hosting the LGA secretariat (Obagaji).')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='wards/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clans', to='wards.ward')),
            ],
            options={
                'verbose_name_plural': 'Clans',
                'ordering': ['ward__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WardContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(help_text='e.g. Ward Officer, Town Union Chairman', max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='wards.ward')),
            ],
            options={
                'ordering': ['ward__name', 'full_name'],
            },
        ),
    ]
