# Generated by Django 5.1.4 on 2026-08-24 12:21

import apps.media_library.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='library/%Y/%m/', validators=[apps.media_library.models.validate_file_size, apps.media_library.models.validate_extension])),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='library/thumbnails/')),
                ('asset_type', models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], editable=False, max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility description — required for images used on public pages.', max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(default=0, editable=False)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
